name: ticket
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.0
  provider: ^6.0.1
  google_maps_flutter: ^2.1.1
  dio: ^4.0.4
  flutter_polyline_points: ^1.0.0
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    # Images
    - assets/images/

    # Icons
    - assets/icons/BottomBar/
    - assets/icons/Buttons/
    - assets/icons/MapPins/
    - assets/icons/Misc/
    - assets/icons/PropertyInfo/
    - assets/icons/Tags/
    - assets/icons/Tickets/
    - assets/icons/TopBar/
    - assets/icons/Auth/


  # Fonts

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
